### ISSUE TITLE
NameError: name 'ULInt32' is not defined

### ISSUE THREAD

**Issue by Beercow** [moyix/pdbparse#31]
I receive the following error when I try to run symchk

C:\>py c:\Python27\Scripts\symchk.py
Traceback (most recent call last):
  File "c:\Python27\Scripts\symchk.py", line 37, in <module>
    from pdbparse.peinfo import *
  File "C:\Python27\lib\site-packages\pdbparse\peinfo.py", line 3, in <module>
    from pdbparse.dbgold import CV_RSDS_HEADER, CV_NB10_HEADER, DebugDirectoryType
  File "C:\Python27\lib\site-packages\pdbparse\dbgold.py", line 4, in <module>
    from pdbparse.pe import IMAGE_SECTION_HEADER
  File "C:\Python27\lib\site-packages\pdbparse\pe.py", line 3, in <module>
    from pdbparse.info import GUID
  File "C:\Python27\lib\site-packages\pdbparse\info.py", line 21, in <module>
    ULInt32("Version"),
NameError: name 'ULInt32' is not defined

**Comment by moyix** [comment]
It looks like as of September 2016 the API of a library we depend on ([Construct](https://construct.readthedocs.io/en/latest/)) has changed drastically. You should install version 2.5.5 instead for now, and hopefully I'll find some time to update to use the newer API at some point (or if you feel like doing this I'd be happy to take a pull request :) ).
