### ISSUE TITLE
Linux install error

### ISSUE THREAD

**Issue by ultrapikachu** [moyix/pdbparse#44]
After setup.py
I'm getting these error when i try run example
```
Traceback (most recent call last):
  File "./symchk.py", line 36, in <module>
    from pdbparse.peinfo import *
  File "/usr/local/lib/python3.6/dist-packages/pdbparse/peinfo.py", line 5, in <module>
    from pdbparse.dbgold import CV_RSDS_HEADER, CV_NB10_HEADER, DebugDirectoryType
  File "/usr/local/lib/python3.6/dist-packages/pdbparse/dbgold.py", line 4, in <module>
    from pdbparse.pe import IMAGE_SECTION_HEADER
  File "/usr/local/lib/python3.6/dist-packages/pdbparse/pe.py", line 6, in <module>
    String("Name", 8),
NameError: name 'String' is not defined
```

**Comment by moyix** [comment]
What version of Construct are you using? I believe there have been some major changes to Construct and we have not updated pdbparse to use the newer version.

**Comment by moyix** [comment]
FYI, this should now be fixed. Please give a try with the latest version.
